// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCoreAssessment.Entities
{
    public partial class DocumentFiles
    {
        public int FileId { get; set; }
        public string FilePath { get; set; }
        public int DocumentId { get; set; }

        public virtual Documents Document { get; set; }
    }
}